package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.awt.Desktop;


public class Reports extends javax.swing.JFrame {

    private Connection connection;

    public Reports() {
        initComponents();
        connectToDatabase();
    }

    private void connectToDatabase() {
        try {
            String url = "jdbc:mysql://localhost:3306/healthcare_db";
            String user = "root";
            String password = "";
            connection = DriverManager.getConnection(url, user, password);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Failed to connect to the database: " + e.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    private void generateAndOpenPDFReport(String query, String reportName,String labelString) {

        Document document = new Document();
        String filePath = reportName+".pdf";
        try {
            // Generate PDF
            PdfWriter.getInstance(document, new FileOutputStream(filePath));
            document.open();
            document.add(new Paragraph(labelString));

            try (PreparedStatement stmt = connection.prepareStatement(query);
                 ResultSet rs = stmt.executeQuery()) {


                while (rs.next()){

                    String content  = String.format("%s :  %s", rs.getMetaData().getColumnName(1), rs.getString(1));

                    document.add(new Paragraph(content));

                }


            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Failed to get reports from DB, Check code or DB Structure.", "Error", JOptionPane.ERROR_MESSAGE);

                return;
            }
            document.close();

            File pdfFile = new File(filePath);
            if (Desktop.isDesktopSupported()) {
                Desktop.getDesktop().open(pdfFile);
                JOptionPane.showMessageDialog(this, "Report generated correctly", "Success", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Desktop is not supported, unable to open PDF.", "Error", JOptionPane.ERROR_MESSAGE);
            }


        } catch (DocumentException | IOException e) {
            JOptionPane.showMessageDialog(this, "Error generating or opening PDF report.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }



    }




    private void generateRevenueReport() {
        String sqlQuery = "SELECT SUM(selling_price * quantity_stock) FROM inventory;";
        generateAndOpenPDFReport(sqlQuery, "Revenue_Report", "Monthly Revenue Report");

    }


    private void generatePatientVisitReport() {
        String sqlQuery = "SELECT COUNT(DISTINCT patient_id) AS unique_patients  FROM appointments;";
        generateAndOpenPDFReport(sqlQuery, "Patient_visits_Report", "Monthly Patient Visits Report");

    }


    private void generateInventoryUsageReport() {
        String sqlQuery = "SELECT drug_name,quantity_stock  FROM inventory;";
        generateAndOpenPDFReport(sqlQuery, "Inventory_usage_report", "Inventory Usage Report");

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        generatePatientReport = new javax.swing.JButton();
        generateRevenueReport = new javax.swing.JButton();
        generateUsageReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Generate Monthly Reports");

        home.setBackground(new java.awt.Color(255, 204, 204));
        home.setText("Home");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        generatePatientReport.setText("Patient visits");
        generatePatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePatientReportActionPerformed(evt);
            }
        });

        generateRevenueReport.setText("Revenue");
        generateRevenueReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateRevenueReportActionPerformed(evt);
            }
        });

        generateUsageReport.setText("Inventory Usage");
        generateUsageReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateUsageReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(generatePatientReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generateUsageReport, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                                        .addComponent(generateRevenueReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(generateRevenueReport)
                                .addGap(39, 39, 39)
                                .addComponent(generatePatientReport)
                                .addGap(40, 40, 40)
                                .addComponent(generateUsageReport)
                                .addContainerGap(349, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(451, 451, 451)
                                                .addComponent(jLabel1)
                                                .addGap(236, 236, 236)
                                                .addComponent(home))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(home))
                                .addGap(30, 30, 30)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(55, Short.MAX_VALUE))
        );
        // --- Start of Custom UI Code ---
        getContentPane().setBackground(new java.awt.Color(240, 240, 240));
        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));

        home.setBackground(new java.awt.Color(51, 153, 255));
        home.setForeground(java.awt.Color.WHITE);
        home.setFocusPainted(false);
        home.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));


        generatePatientReport.setBackground(new java.awt.Color(51, 153, 255));
        generatePatientReport.setForeground(java.awt.Color.WHITE);
        generatePatientReport.setFocusPainted(false);
        generatePatientReport.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));


        generateRevenueReport.setBackground(new java.awt.Color(51, 153, 255));
        generateRevenueReport.setForeground(java.awt.Color.WHITE);
        generateRevenueReport.setFocusPainted(false);
        generateRevenueReport.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));


        generateUsageReport.setBackground(new java.awt.Color(51, 153, 255));
        generateUsageReport.setForeground(java.awt.Color.WHITE);
        generateUsageReport.setFocusPainted(false);
        generateUsageReport.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));


        // --- End of Custom UI Code ---
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UI homeWindow = new UI();
        homeWindow.setVisible(true);

        // Close the current Manage_suppliers window
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void generatePatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePatientReportActionPerformed
        generatePatientVisitReport();
    }//GEN-LAST:event_generatePatientReportActionPerformed

    private void generateRevenueReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateRevenueReportActionPerformed
        generateRevenueReport();
    }//GEN-LAST:event_generateRevenueReportActionPerformed

    private void generateUsageReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateUsageReportActionPerformed
        generateInventoryUsageReport();
    }//GEN-LAST:event_generateUsageReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Reports().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generatePatientReport;
    private javax.swing.JButton generateRevenueReport;
    private javax.swing.JButton generateUsageReport;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}