package view;

import javax.swing.JOptionPane;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.awt.Desktop;



public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        System.out.println("Welcome!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Manage_Patient_Records = new javax.swing.JButton();
        Manage_Doctor_Schedules = new javax.swing.JButton();
        Manage_Pharmacy_Inventory = new javax.swing.JButton();
        Generate_Monthly_Reports = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Book_Appointments = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Manage_Patient_Records.setBackground(new java.awt.Color(153, 255, 153));
        Manage_Patient_Records.setText("Manage Patient Records ");
        Manage_Patient_Records.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Patient_RecordsActionPerformed(evt);
            }
        });

        Manage_Doctor_Schedules.setBackground(new java.awt.Color(255, 204, 204));
        Manage_Doctor_Schedules.setText("Manage Doctor Schedules");
        Manage_Doctor_Schedules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Doctor_SchedulesActionPerformed(evt);
            }
        });

        Manage_Pharmacy_Inventory.setBackground(new java.awt.Color(153, 153, 255));
        Manage_Pharmacy_Inventory.setText("Manage Pharmacy Inventory");
        Manage_Pharmacy_Inventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Manage_Pharmacy_InventoryActionPerformed(evt);
            }
        });

        Generate_Monthly_Reports.setBackground(new java.awt.Color(204, 255, 255));
        Generate_Monthly_Reports.setText("Generate Monthly Reports");
        Generate_Monthly_Reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Generate_Monthly_ReportsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Health Care Management System");

        Book_Appointments.setBackground(new java.awt.Color(255, 255, 204));
        Book_Appointments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Book_Appointments.setText("Book Appointments");
        Book_Appointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_AppointmentsActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(155, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(136, 136, 136))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(316, 316, 316)
                                                .addComponent(Book_Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(85, 85, 85)
                                                .addComponent(Manage_Patient_Records)
                                                .addGap(18, 18, 18)
                                                .addComponent(Manage_Doctor_Schedules, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29)
                                                .addComponent(Manage_Pharmacy_Inventory)
                                                .addGap(18, 18, 18)
                                                .addComponent(Generate_Monthly_Reports))
                                )
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Manage_Doctor_Schedules, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Manage_Pharmacy_Inventory, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Generate_Monthly_Reports, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Manage_Patient_Records, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(Book_Appointments, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)

                                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );


        // --- Start of Custom UI Code ---
        getContentPane().setBackground(new java.awt.Color(240, 240, 240));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder());


        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));

        Manage_Patient_Records.setBackground(new java.awt.Color(51, 153, 255));
        Manage_Patient_Records.setForeground(java.awt.Color.WHITE);
        Manage_Patient_Records.setFocusPainted(false);
        Manage_Patient_Records.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));


        Manage_Doctor_Schedules.setBackground(new java.awt.Color(51, 153, 255));
        Manage_Doctor_Schedules.setForeground(java.awt.Color.WHITE);
        Manage_Doctor_Schedules.setFocusPainted(false);
        Manage_Doctor_Schedules.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));

        Manage_Pharmacy_Inventory.setBackground(new java.awt.Color(51, 153, 255));
        Manage_Pharmacy_Inventory.setForeground(java.awt.Color.WHITE);
        Manage_Pharmacy_Inventory.setFocusPainted(false);
        Manage_Pharmacy_Inventory.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));


        Generate_Monthly_Reports.setBackground(new java.awt.Color(51, 153, 255));
        Generate_Monthly_Reports.setForeground(java.awt.Color.WHITE);
        Generate_Monthly_Reports.setFocusPainted(false);
        Generate_Monthly_Reports.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));


        Book_Appointments.setBackground(new java.awt.Color(51, 153, 255));
        Book_Appointments.setForeground(java.awt.Color.WHITE);
        Book_Appointments.setFocusPainted(false);
        Book_Appointments.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51,153,255)),javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        // --- End of Custom UI Code ---


        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Manage_Patient_RecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Patient_Records_OrdersActionPerformed
        // TODO add your handling code here:
        Manage_patient_records managePatientRecordsWindow = new Manage_patient_records();
        managePatientRecordsWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_Patient_RecordsActionPerformed

    private void Manage_Doctor_SchedulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Doctor_SchedulesActionPerformed
        Manage_doctor_schedules manageDoctorSchedulesWindow = new Manage_doctor_schedules();
        manageDoctorSchedulesWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_Doctor_SchedulesActionPerformed

    private void Manage_Pharmacy_InventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Manage_Pharmacy_InventoryActionPerformed
        // TODO add your handling code here:
        Manage_pharmacy_inventory managePharmacyInventoryWindow = new Manage_pharmacy_inventory();
        managePharmacyInventoryWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Manage_Pharmacy_InventoryActionPerformed

    private void Generate_Monthly_ReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Generate_Monthly_ReportsActionPerformed
        // TODO add your handling code here:
        Generate_reports generateReportsWindow = new Generate_reports ();
        generateReportsWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Generate_Monthly_ReportsActionPerformed

    private void Book_AppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_AppointmentsActionPerformed
        BookAppointments manageBook_AppointmentsWindow = new BookAppointments();
        manageBook_AppointmentsWindow.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Book_AppointmentsActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Book_Appointments;
    private javax.swing.JButton Manage_Patient_Records;
    private javax.swing.JButton Generate_Monthly_Reports;
    private javax.swing.JButton Manage_Pharmacy_Inventory;
    private javax.swing.JButton Manage_Doctor_Schedules;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;

}